### ISSUE TITLE
Fails on WSL Linux-filesystem paths

### ISSUE THREAD

**Issue by ses4j** [mbinic/vscode-tgit#13] opened 2020-10-21 13:57 UTC
I increasingly have to do work on Windows under WSL.  Trying to run, eg, tgit.diff with a file mounted on the Linux filesystem doesn't work, unsurprisingly.  It is theoretically possible, because any WSL path can be converted to a Windows path.   One approach is to use the `wslpath` command.  For instance, for me to get Beyond Compare to work as a git difftool I use this:

```
[difftool "bc3"]
        # old way 
        # cmd = \"c:/Program Files/Beyond Compare 4/BCompare.exe\" \"$LOCAL\" \"$REMOTE\" -solo
        # new way that supports WSL
        cmd="/mnt/c/Program\\ Files/Beyond\\ Compare\\ 4/BComp.exe" "$(wslpath -aw $LOCAL)" "$(wslpath -aw $REMOTE)" -solo
```

Here's `wslpath` in action:

```
user@sheyn:~/wc/ventus$ wslpath
wslpath: Invalid argument
Usage:
    -a    force result to absolute path format
    -u    translate from a Windows path to a WSL path (default)
    -w    translate from a WSL path to a Windows path
    -m    translate from a WSL path to a Windows path, with '/' instead of '\'

EX: wslpath 'c:\users'
user@sheyn:~/wc/ventus$ wslpath -aw ~
\\wsl$\Ubuntu\home\user```

**Comment by mbinic** [comment] 2020-10-21 21:57
Thanks for the detailed report! I agree, wslpath looks promising. I'll give it a shot over the weekend, and release an update if it pans out. Don't hesitate to beat me to it though ;)

**Comment by ses4j** [comment] 2020-12-02 14:46
@mbinic Any luck?  Or, I haven't looked closely at your code, any suggestion as to where/how this change would be made?

**Comment by mbinic** [comment] 2020-12-19 16:56
Sorry @ses4j , busy days... Looking more closely at this, it appears to be the same root cause as issue #2 - trying to start TortoiseGitProc with the working directory set to a network path, i.e. one starting with \\.

I've made a small change in the `run` method on line 109 of `src/TGit.ts`, to always supply the `path` argument instead of passing the cwd parameter to `exec`. I'll test it some more and release an update if it works out.

**Comment by mbinic** [comment] 2020-12-19 18:11
Version 1.4.0 released, this should now be fixed.
@ses4j, please let me know if everything's ok at your end and I can close this issue.

**Closed** 2021-04-03 20:48 UTC
